Default: &defaults
  host: "*4" # any IPv4 host
  # note that devel port is always 3000
  port: 8496
  approot: "http://localhost:8496"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
