Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: (c) Functor-static Four, 2013
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 8496
  approot: "http://ec2-54-250-187-247.ap-northeast-1.compute.amazonaws.com:8496"
  <<: *defaults
