#!/usr/bin/env runhaskell

import Control.Monad
import System.Environment
import System.Process
import Text.Printf

main :: IO ()
main = do
  (para:rangeStr:argv) <- getArgs
  let indices :: [Int]
      indices = [a..b]
      (a,b) = read rangeStr
      
  
  ec2s <- fmap (map (unwords.words) . lines )$ readFile "ec2-instances"
  forM_ [ec2s!!i | i <- indices] $ \url -> do
    printf "ssh -i oregon-jkey.pem ubuntu@%s '%s'%s\n" url (unwords argv)
      (if para=="P" then " &" else "")
